name: Docker

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Publish Docker image to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: korrecte/korrecte
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}