name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Fmt
      run: cargo fmt -- --check
    - name: Publish Docker image to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: korrecte/korrecte
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}